# Generated by Django 4.2.16 on 2026-04-28 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payout_engine', '0002_new_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='payout_engi_key_8777c6_idx',
            old_name='payout_engi_key_35a123_idx',
        ),
    ]
